agenda/urls.py
from django.urls import path

from .views import (VistaEventoEnDetalle, VistaListaEvento, VistaReporteGeneralEvento)

app_name = 'agenda'
urlpatterns = [
    path('agenda/', VistaListaEvento.as_view(), name='index'),
    path('agenda-en-detalle/<int:pk>', VistaEventoEnDetalle.as_view(), name='detalle'),
    path('reporte-general-agenda/', VistaReporteGeneralEvento.as_view(), name='reporte-general'),
]

certipro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tablero.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('asistentes/', include('asistentes.urls')),
    path('auditorios/', include('auditorios.urls')),
    path('temario/', include('temario.urls')),
    path('agenda/', include('agenda.urls')),
    path('certificados/', include('certificados.urls')),
    path('usuario/', include('nucleo.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('debugg/', include(debug_toolbar.urls)),
    ] + urlpatterns

agenda/models.py
from django.db import models


class TipoEvento(models.Model):
    """Almacena el tipo de evento (curso, taller, charla, conferencia, etc).

    Args:
        Model (class): Modelo base de Django.

    Returns:
        string: Nombre del tipo de evento.
    """
    tipoevento_nombre = models.CharField('nombre del tipo de evento', max_length=50)

    class Meta:
        verbose_name = 'Tipo de Evento'
        verbose_name_plural = 'Tipos de Eventos'
        ordering = ['tipoevento_nombre',]

    def __str__(self):
        return self.tipoevento_nombre


class Evento(models.Model):
    """Almacena un evento en la agenda.

    Args:
        Model (class): Modelo base de Django.

    Returns:
        string: Tipo de evento y tema tratado.
    """
    asistentes = models.ManyToManyField('asistentes.Asistente')
    tema_tratado = models.ForeignKey('temario.DetalleTema', on_delete=models.CASCADE)
    tipo_evento = models.ForeignKey(TipoEvento, on_delete=models.CASCADE, verbose_name='tipo de evento')
    auditorio = models.ForeignKey('auditorios.Auditorio', on_delete=models.CASCADE)
    fecha_inicio = models.DateField('empieza el', auto_now=False, auto_now_add=False)
    fecha_fin = models.DateField('culmina el', auto_now=False, auto_now_add=False)

    class Meta:
        verbose_name = 'Evento'
        verbose_name_plural = 'Eventos'
        ordering = ['tipo_evento', 'tema_tratado']

    def __str__(self):
        return f'{self.tipo_evento}: {self.tema_tratado}'

agenda/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin

from .filters import FiltroEvento
from .models import Evento, TipoEvento
from .tables import TablaEvento


class VistaListaEvento(LoginRequiredMixin, SingleTableMixin, FilterView):
    """Renderiza la agenda de los eventos registrados en el sistema,
    en formato de tabla.

    Args:
        LoginRequiredMixin (class): Verifica que el usuario esté autentificado.
        SingleTableMixin (class): Agrega una tabla HTMl al contexto.
        FilterView (class): Renderiza los filtros de búsqueda.

    Returns:
        string: HTML de la vista.
    """
    model = Evento
    template_name = 'agenda/lista-agenda.html'
    table_class = TablaEvento
    paginate_by = 10
    filterset_class = FiltroEvento

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_title'] = 'CertiPro | Eventos'
        context['page_title'] = 'Eventos'
        context['content_title'] = 'Eventos registrados'
        context['url_reporte'] = 'tablero:index'
        context['url_admin'] = 'admin:agenda_evento_changelist'
        return context


class VistaEventoEnDetalle(LoginRequiredMixin, DetailView):
    """Renderiza los detalles de un evento de la agenda en un modal bootstrap.

    Args:
        LoginRequiredMixin (class): Verifica que el usuario esté autentificado.
        DetailView (class): Vista genérica detallada de Django.
    """
    model = Evento
    template_name = 'agenda/detalle-agenda.html'


class VistaReporteGeneralEvento(DetailView):
    pass

agenda/templates/agenda/botones_acciones.html
<a href="#" class="btn btn-primary btn-circle btn-sm btn_info" title="Ver más" data-url-detalle="{% url 'agenda:detalle' record.id %}">
  <i class="fas fa-eye"></i>
</a>
<a href="{% url 'admin:agenda_evento_change' record.id %}" target="_blank" class="btn btn-success btn-circle btn-sm" title="Editar en el Administrador">
  <i class="fas fa-edit"></i>
</a>

agenda/templates/agenda/detalle-agenda.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="moreInfoModalLabel"><em>{{ object.tipo_evento }}: {{ object.tema_tratado }}</em></h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Lugar: <em>{{ object.auditorio }}</em></li>
          <li class="list-group-item">Comienza: <em>{{ object.fecha_inicio }}</em></li>
          <li class="list-group-item">Termina: <em>{{ object.fecha_fin }}</em></li>
          <li class="list-group-item">Asistentes:
            <ul class="list-group list-group-flush">
              {% for persona in object.asistentes.all %}
              <li class="list-group-item"><em>{{ persona }}</em></li>
              {% endfor %}
            </ul>
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cerrar</button>
        <a class="btn btn-success" href="{% url 'admin:agenda_evento_change' object.id %}" target="_blank">Editar</a>
      </div>
    </div>
  </div>

agenda/templates/agenda/lista-agenda.html
{% extends "tablero/base.html" %}

{% block nav-item-eventos %}<li class="nav-item active">{% endblock %}