agenda/urls.py
from django.urls import path

from .views import (VistaEventoEnDetalle, VistaListaEvento, VistaReporteGeneralEvento)

app_name = 'agenda'
urlpatterns = [
    path('agenda/', VistaListaEvento.as_view(), name='index'),
    path('agenda-en-detalle/<int:pk>', VistaEventoEnDetalle.as_view(), name='detalle'),
    path('reporte-general-agenda/', VistaReporteGeneralEvento.as_view(), name='reporte-general'),
]

asistentes/urls.py
from django.urls import path

from .views import (VistaAsistenteEnDetalle, VistaListaAsistentes, VistaReporteGeneralAsistentes)

app_name = 'asistentes'
urlpatterns = [
    path('asistentes/', VistaListaAsistentes.as_view(), name='index'),
    path('asistente-en-detalle/<int:pk>', VistaAsistenteEnDetalle.as_view(), name='detalle'),
    path('reporte-general-asistentes/', VistaReporteGeneralAsistentes.as_view(), name='reporte-general'),
]

auditorios/urls.py
from django.urls import path

from .views import VistaAuditorioEnDetalle, VistaListaAuditorios

app_name = 'auditorios'
urlpatterns = [
    path('auditorios/', VistaListaAuditorios.as_view(), name='index'),
    path('auditorio-en-detalle/<int:pk>', VistaAuditorioEnDetalle.as_view(), name='detalle'),
]

certipro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tablero.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('asistentes/', include('asistentes.urls')),
    path('auditorios/', include('auditorios.urls')),
    path('temario/', include('temario.urls')),
    path('agenda/', include('agenda.urls')),
    path('certificados/', include('certificados.urls')),
    path('usuario/', include('nucleo.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('debugg/', include(debug_toolbar.urls)),
    ] + urlpatterns

nucleo/urls.py
from django.urls import path
from .views import ModificacionDePerfilDeUsuario

app_name = 'nucleo'
urlpatterns = [
    path('usuario/mi-perfil/<int:pk>', ModificacionDePerfilDeUsuario.as_view(), name='perfilusuario')
]

tablero/urls.py
from django.urls import path

from tablero import views

app_name = 'tablero'
urlpatterns = [
    path('', views.index, name='index'),
    path('reporte-general/', views.reporte, name='reporte-general'),
]

temario/urls.py
from django.urls import path

from .views import VistaListaTemario, VistaTemarioEnDetalle

app_name = 'temario'
urlpatterns = [
    path('temario/', VistaListaTemario.as_view(), name='index'),
    path('temario-en-detalle/<int:pk>', VistaTemarioEnDetalle.as_view(), name='detalle'),
]

tablero/models.py
from django.db import models

# Create your models here.

tablero/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from asistentes.models import Asistente



@login_required
def index(request):
    """Página de inicio del sitio web o proyecto.

    Arguments:
        request {object} -- Objeto HttpRequest

    Returns:
        object -- Objeto HttpResponse con plantilla y contexto renderizados.
    """
    minifichas_cuantificadoras = {
        'ficha_asistentes': {
            'clase_css': 'primary',
            'titulo': 'Asistentes registrados',
            'cantidad': Asistente.objects.count(),
            'icono': 'fas fa-users'
        },
    }
    context = {
        'site_title': 'CertiPro | Tablero',
        'page_title': 'Tablero',
        'minifichas': minifichas_cuantificadoras,
        'url_reporte': 'tablero:reporte-general',
        'url_admin': 'admin:index',
    }

    return render(request, 'tablero/index.html', context=context)


def reporte(request):
    """TODO definir esta vista para los reportes generales.

    Arguments:
        request {object} -- Objeto HttpResponse con plantilla y contexto renderizados.
    """
    pass

tablero/templates/tablero/base.html
{% load i18n static %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:'es-ve' }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="CertiPro">
  <meta name="author" content="Maikel Carballo">
  {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}

  <title>{% block title %}{{ site_title|default:_('CertiPro') }}{% endblock %}</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">

  {% block extrastyle %}{% endblock %}
  {% block extrahead %}{% endblock %}

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/g-fonts.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>
{% load i18n %}

{% block body-page %}
<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'tablero:index' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-scroll"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{{ site_header|default:_('CertiPro') }} <sup>0.1</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Tablero -->
      {% block nav-item-tablero %}
      <li class="nav-item">
      {% endblock nav-item-tablero %}
        <a class="nav-link" href="{% url 'tablero:index' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Tablero</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Favoritos
      </div>

      <!-- Nav Item - Certificados -->
      {% block nav-item-certificados %}
      <li class="nav-item">
      {% endblock nav-item-certificados %}
        <a class="nav-link" href="{% url 'certificados:index' %}">
          <i class="fas fa-fw fa-certificate"></i>
          <span>Certificados</span></a>
      </li>

      <!-- Nav Item - Asistentes -->
      {% block nav-item-asistentes %}
      <li class="nav-item">
      {% endblock nav-item-asistentes %}
        <a class="nav-link" href="{% url 'asistentes:index' %}">
          <i class="fas fa-fw fa-users"></i>
          <span>Asistentes</span></a>
      </li>

      <!-- Nav Item - Eventos -->
      {% block nav-item-eventos %}
      <li class="nav-item">
      {% endblock nav-item-eventos %}
        <a class="nav-link" href="{% url 'agenda:index' %}">
          <i class="fas fa-fw fa-calendar-check"></i>
          <span>Eventos</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Maestros
      </div>

      <!-- Nav Item - Temario -->
      {% block nav-item-temario %}
      <li class="nav-item">
      {% endblock nav-item-temario %}
        <a class="nav-link" href="{% url 'temario:index' %}">
          <i class="fas fa-fw fa-clipboard-list"></i>
          <span>Temario</span></a>
      </li>

      <!-- Nav Item - Auditorios -->
      {% block nav-item-auditorios %}
      <li class="nav-item">
      {% endblock nav-item-auditorios %}
        <a class="nav-link" href="{% url 'auditorios:index' %}">
          <i class="fas fa-fw fa-university"></i>
          <span>Auditorios</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>
            {% block usertools %}

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{% block welcome-msg %}{% trans 'Welcome,' %} {% firstof user.get_short_name user.get_username %}{% endblock %}</span>
                <img class="img-profile rounded-circle" src="{% if user.avatar %}{{ user.avatar.url }}{% else %}#{% endif %}">
              </a>
              {% block userlinks %}
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                {% if user.has_usable_password %}
                <a class="dropdown-item" href="{% url 'admin:password_change' %}">
                  <i class="fas fa-key fa-sm fa-fw mr-2 text-gray-400"></i>
                  {% trans 'Change password' %}
                </a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'nucleo:perfilusuario' user.id %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Perfil
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  {% trans 'Log out' %}
                </a>
              </div>
              {% endblock %}
            </li>
            {% endblock %}

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          {% block page-heading %}
          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{{ page_title }}</h1>
            <div class="d-sm-flex align-items-center justify-content-end">
              {% block page-heading-tools %}
              <a href="{% url url_admin %}" class="d-none d-sm-inline-block btn btn-sm btn-info shadow-sm ml-3" target="_blank"><i class="fas fa-external-link-alt fa-sm text-white-50"></i> Ir al Administrador</a>
              {% endblock page-heading-tools %}
            </div>
          </div>
          {% endblock page-heading %}

          {% if notify_alert %}
          <div class="row">
            <div class="col-lg-12">
              <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{ notify_alert.strong }}</strong> {{ notify_alert.text }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            </div>
          </div>
          {% endif %}

          {% block content-on-row %}{% endblock content-on-row %}
          {% block content-on-table %}
          <!-- Data Table -->
          <div class="card shadow h-100 mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">{{ content_title }}</h6>
            </div>
            <div class="card-body">
              {% load bootstrap4 %}
              {% if filter %}
              <form action="" method="get" class="form-inline">
                  {% bootstrap_form filter.form layout='inline' form_group_class='mr-sm-2 mb-2' %}
                  {% buttons form_group_class='mr-sm-2 mb-2' %}
                  <button class="btn btn-primary"><i class="fas fa-filter fa-sm"></i> Filtrar</button>
                  {% endbuttons %}
              </form>
              {% endif %}
              <br>
              {% load render_table from django_tables2 %}
              {% render_table table %}
            </div>
          </div>
          {% endblock content-on-table %}
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      {% block footer %}
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Maikel Carballo 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->
      {% endblock footer %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{% trans 'Ready to Leave?' %}</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">{% trans 'Select "Log out" below if you are ready to end your current session.' %}</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="{% url 'logout' %}">{% trans 'Log out' %}</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Data Modal-->
  <div class="modal fade" id="moreInfoModal" tabindex="-1" role="dialog" aria-labelledby="moreInfoModalLabel" aria-hidden="true">
  </div>

  <!-- Error Modal-->
  <div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="errorModalLabel"></h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>

  {% block all-pages-scripts %}
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  {% endblock all-pages-scripts %}

  {% block page-level-scripts %}
  <script>
    (function($) {
      "use strict"; // Start of use strict

      $('.btn_info').click(function(e) {
          e.preventDefault();
          $.ajax({
              method: 'GET',
              url: $(this).data('urlDetalle'),
              dataType: 'html',
              statusCode: {
                404: function() {
                  $('#errorModalLabel').text('404');
                  $('#errorModal .modal-body').text('No se encuentra.');
                },
                500: function() {
                  $('#errorModalLabel').text('500');
                  $('#errorModal .modal-body').text('Problema encontrado. Si persiste, comuníquese con el Dpto. de Asistencia al Usuario.');
                },
              }
          })
          .done(function(r) {
              $('#moreInfoModal').html(r);
              $('#moreInfoModal').modal();
          })
          .fail(function(r) {
              // Lo ideal sería aprovechar el fallo para ¿hacerle un seguimiento a nivel de sistema?.
          });
      });

    })(jQuery); // End of use strict
  </script>
  {% endblock page-level-scripts %}

</body>
{% endblock body-page %}

</html>

tablero/templates/tablero/base_site.html
{% extends "tablero/base.html" %}

{% block title %}{{ site_title|default:_('CertiPro: Tablero') }}{% endblock %}

{% block sidebar-nav %}
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-scroll"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{{ site_header|default:_('CertiPro') }} <sup>0.1</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Tablero -->
      <li class="nav-item{% if request.path == '/' %} active{% endif %}">
        <a class="nav-link" href="{% url 'index' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Tablero</span></a>
      </li>

  {% if modulos %}
    {% for nombre_grupo, menu in modulos.items %}
      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        {{ nombre_grupo }}
      </div>

      {% for nombre_subrupo, submenu in menu.items %}
      <!-- Nav Item - Collapsable Menu -->
      <li class="nav-item {{ submenu.opciones.estatus }}">
        <a class="nav-link {{ submenu.opciones.plegado }}"{% if submenu.opciones.id %} href="#" data-toggle="collapse" data-target="#{{ submenu.opciones.id }}" aria-expanded="{{ submenu.opciones.expandido }}" aria-controls="{{ submenu.opciones.id }}"{% else %} href="{% url submenu.opciones.url %}"{% endif %}>
          <i class="{{ submenu.opciones.icono }}"></i>
          <span>{{ nombre_subrupo }}</span>
        </a>
        {% if submenu.submenu %}
        <div id="{{ submenu.opciones.id }}" class="collapse {{ submenu.opciones.mostrar }}" aria-labelledby="headingMenu" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            {{ submenu.opciones.encabezado }}
            {% for opcion,aspecto in submenu.submenu.items %}
            <a class="collapse-item {{ aspecto.estatus }}" href="{% url aspecto.url %}">{{ opcion }}</a>
            {% endfor %}
          </div>
        </div>
        {% endif %}
      </li>
      {% endfor %}
    {% endfor %}
  {% endif %}

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->
{% endblock %}

{% block object-tools %}
<div class="d-sm-flex align-items-center justify-content-end">
  <a href="{% url url_reporte %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm ml-3"><i class="fas fa-download fa-sm text-white-50"></i> Generar Reporte</a>
  <a href="{% url url_admin %}" class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm ml-3" target="_blank"><i class="fas fa-external-link-alt fa-sm text-white-50"></i> Ir al Administrador</a>
</div>
{% endblock %}

tablero/templates/tablero/index.html
{% extends "tablero/base.html" %}
{% load i18n static %}

{% block nav-item-tablero %}<li class="nav-item active">{% endblock %}

{% block content-on-row %}
          <!-- Content Row -->
          <div class="row">
            {% for ficha, f in minifichas.items %}
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-{{ f.clase_css }} shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-{{ f.clase_css }} text-uppercase mb-1">{{ f.titulo }}</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{ f.cantidad }}</div>
                    </div>
                    <div class="col-auto">
                      <i class="{{ f.icono }} fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Content Column -->
            <div class="col-lg-12 mb-4">

              <!-- En Construcción -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">En Construcción</h6>
                </div>
                <div class="card-body">
                  <div class="text-center">
                    <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{% static 'img/undraw_under_construction_46pa.svg' %}" alt="">
                  </div>
                  <p>CertiPro es un sistema informático diseñado para gestionar (generar, consultar, editar...) de manera
                    simple, certificados de asistencia a eventos didácticos o de otro tipo.
                  </p>
                  <p class="mb-0">El front-end se apoya en la plantilla SB Admin 2, la cual está basada en Bootstrap 4,
                    HTML5 y otras herramientas web estándares. En el back-end está desarrollado en Python 3 usando como
                    framework web Django 3.
                  </p>
                  <a target="_blank" rel="nofollow" href="https://twitter.com/maikelitus">Más información &rarr;</a>
                </div>
              </div>

            </div>
          </div>
{% endblock %}
{% block content-on-table %}{% endblock %}