agenda/urls.py
from django.urls import path

from .views import (VistaEventoEnDetalle, VistaListaEvento, VistaReporteGeneralEvento)

app_name = 'agenda'
urlpatterns = [
    path('agenda/', VistaListaEvento.as_view(), name='index'),
    path('agenda-en-detalle/<int:pk>', VistaEventoEnDetalle.as_view(), name='detalle'),
    path('reporte-general-agenda/', VistaReporteGeneralEvento.as_view(), name='reporte-general'),
]

asistentes/urls.py
from django.urls import path

from .views import (VistaAsistenteEnDetalle, VistaListaAsistentes, VistaReporteGeneralAsistentes)

app_name = 'asistentes'
urlpatterns = [
    path('asistentes/', VistaListaAsistentes.as_view(), name='index'),
    path('asistente-en-detalle/<int:pk>', VistaAsistenteEnDetalle.as_view(), name='detalle'),
    path('reporte-general-asistentes/', VistaReporteGeneralAsistentes.as_view(), name='reporte-general'),
]

certipro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tablero.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('asistentes/', include('asistentes.urls')),
    path('auditorios/', include('auditorios.urls')),
    path('temario/', include('temario.urls')),
    path('agenda/', include('agenda.urls')),
    path('certificados/', include('certificados.urls')),
    path('usuario/', include('nucleo.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('debugg/', include(debug_toolbar.urls)),
    ] + urlpatterns

asistentes/models.py
from django.contrib.humanize.templatetags.humanize import intcomma
from django.core.validators import MinValueValidator
from django.db import models


class Asistente(models.Model):
    """Almacena los datos de la persona que `ha participado en un evento`.

    Arguments:
        models (class) -- Modelo base de Django.

    Returns:
        string -- Maikel Carballo - V 12345678 (ejemplo).
    """

    NACIONALIDAD_V = 'V'
    NACIONALIDAD_E = 'E'
    NACIONALIDADES = [
        (NACIONALIDAD_V, 'Venezolana(o)'),
        (NACIONALIDAD_E, 'Extranjera(o)'),
    ]
    nacionalidad = models.CharField(max_length=1, choices=NACIONALIDADES, default=NACIONALIDAD_V)
    numero_ci = models.PositiveIntegerField('número de CI', unique=True, validators=[MinValueValidator(1),])
    nombres = models.CharField('nombre(s)', max_length=200, help_text='Ej.: Ana María')
    apellidos = models.CharField('apellido(s)', max_length=200, help_text='Ej.: Pérez Pérez')

    class Meta:
        verbose_name = 'Asistente'
        verbose_name_plural = 'Asistentes'
        ordering = ['nombres']

    def __str__(self):
        return f'{self.nombres} {self.apellidos} - {self.nacionalidad} {self.numero_ci_humano}'

    @property
    def numero_ci_humano(self):
        """Formatea el número de cédula de identidad con separador de miles
        según la configuración regional establecida.

        Returns:
            string -- Ejemplo: 99.999.999
        """
        return intcomma(self.numero_ci)

    def numero_ci_humano_admin(self):
        """Formatea el número de cédula de identidad con separador de miles
        según la configuración regional establecida, en el admin.

        Returns:
            string -- Ejemplo: 99.999.999
        """
        return intcomma(self.numero_ci)
    numero_ci_humano_admin.admin_order_field = 'numero_ci'
    numero_ci_humano_admin.short_description = 'número de CI'

asistentes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin

from .filters import FiltroAsistente
from .models import Asistente
from .tables import TablaAsistentes


class VistaListaAsistentes(LoginRequiredMixin, SingleTableMixin, FilterView):
    """Renderiza el catálogo/listado de asistentes registrados en el sistema,
    en formato de tabla.

    Arguments:
        ListView {class} -- Vista de lista genérica de Django.
    """
    model = Asistente
    template_name = 'asistentes/lista-asistentes.html'
    table_class = TablaAsistentes
    paginate_by = 10
    filterset_class = FiltroAsistente

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_title'] = 'CertiPro | Asistentes'
        context['page_title'] = 'Asistentes'
        context['content_title'] = 'Asistentes registrados'
        context['url_reporte'] = 'asistentes:reporte-general'
        context['url_admin'] = 'admin:asistentes_asistente_changelist'
        return context


class VistaAsistenteEnDetalle(LoginRequiredMixin, DetailView):
    """Renderiza el registro detallado de un asistente particular.

    Arguments:
        DetailView {class} -- Vista detallada genérica de Django.
    """
    model = Asistente
    template_name = 'asistentes/detalle-asistente.html'


class VistaReporteGeneralAsistentes(DetailView):
    pass

asistentes/templates/asistentes/botones_acciones.html
<a href="#" class="btn btn-primary btn-circle btn-sm btn_info" title="Ver más" data-url-detalle="{% url 'asistentes:detalle' record.id %}">
  <i class="fas fa-eye"></i>
</a>
<a href="{% url 'admin:asistentes_asistente_change' record.id %}" target="_blank" class="btn btn-success btn-circle btn-sm" title="Editar en el Administrador">
  <i class="fas fa-edit"></i>
</a>

asistentes/templates/asistentes/detalle-asistente.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="moreInfoModalLabel"><em>{{ object.nombres }} {{ object.apellidos }}</em></h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group list-group-flush">
        {% for sigla, nacionalidad in object.NACIONALIDADES %}
            {% if sigla == object.nacionalidad %}
            <li class="list-group-item">Nacionalidad: <em>{{ nacionalidad }}</em></li>
            {% endif %}
        {% endfor %}

        {% if not object.nacionalidad %}
            <li class="list-group-item">Nacionalidad: <em>No ha sido definida.</em></li>
        {% endif %}
            <li class="list-group-item">Número de Cédula de Identidad: <em>{{ object.numero_ci_humano }}</em></li>
          </ul>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cerrar</button>
        <a class="btn btn-success" href="{% url 'admin:asistentes_asistente_change' object.id %}" target="_blank">Editar</a>
      </div>
    </div>
  </div>

asistentes/templates/asistentes/lista-asistentes.html
{% extends "tablero/base.html" %}

{% block nav-item-asistentes %}<li class="nav-item active">{% endblock %}