agenda/urls.py
from django.urls import path

from .views import (VistaEventoEnDetalle, VistaListaEvento, VistaReporteGeneralEvento)

app_name = 'agenda'
urlpatterns = [
    path('agenda/', VistaListaEvento.as_view(), name='index'),
    path('agenda-en-detalle/<int:pk>', VistaEventoEnDetalle.as_view(), name='detalle'),
    path('reporte-general-agenda/', VistaReporteGeneralEvento.as_view(), name='reporte-general'),
]

certipro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tablero.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('asistentes/', include('asistentes.urls')),
    path('auditorios/', include('auditorios.urls')),
    path('temario/', include('temario.urls')),
    path('agenda/', include('agenda.urls')),
    path('certificados/', include('certificados.urls')),
    path('usuario/', include('nucleo.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('debugg/', include(debug_toolbar.urls)),
    ] + urlpatterns

temario/urls.py
from django.urls import path

from .views import VistaListaTemario, VistaTemarioEnDetalle

app_name = 'temario'
urlpatterns = [
    path('temario/', VistaListaTemario.as_view(), name='index'),
    path('temario-en-detalle/<int:pk>', VistaTemarioEnDetalle.as_view(), name='detalle'),
]

temario/models.py
from django.core.validators import MinValueValidator
from django.db import models
from tinymce import models as tinymce_models


class Tema(models.Model):
    """Almacena el tema a tratar.

    Args:
        Model (class): Modelo base de Django.

    Returns:
        string: Título del tema.
    """
    titulo = models.CharField('título del tema', max_length=200)
    subtitulo = models.CharField('subtítulo del tema', max_length=250, blank=True)

    class Meta:
        verbose_name = 'Tema'
        verbose_name_plural = 'Temas'
        ordering = ['titulo',]

    def __str__(self):
        return self.titulo


class DetalleTema(models.Model):
    """Almacena el contenido programático y otros aspectos de un tema.

    Args:
        Model (class): Modelo base de Django.

    Returns:
        string: Título del tema (y edición).
    """
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE)
    horas_academicas = models.SmallIntegerField('horas académicas', validators=[MinValueValidator(8),])
    edicion = models.CharField('edición', max_length=50, help_text='Ej.: 2da. edición')
    contenido = tinymce_models.HTMLField(verbose_name='contenido programático',)

    class Meta:
        verbose_name = 'Detalle del Tema'
        verbose_name_plural = 'Detalles del Tema'
        ordering = ['tema',]

    def __str__(self):
        return f'{self.tema} ({self.edicion})'

temario/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin

from .filters import FiltroTemario
from .models import DetalleTema, Tema
from .tables import TablaTemario


class VistaListaTemario(LoginRequiredMixin, SingleTableMixin, FilterView):
    """Renderiza el catálogo/listado de temas registrados en el sistema,
    en formato de tabla.

    Args:
        LoginRequiredMixin (class): Verifica que el usuario esté autentificado.
        SingleTableMixin (class): Agrega una tabla HTMl al contexto.
        FilterView (class): Renderiza los filtros de búsqueda.

    Returns:
        string: HTML de la vista.
    """
    model = Tema
    template_name = 'temario/lista-temario.html'
    table_class = TablaTemario
    paginate_by = 10
    filterset_class = FiltroTemario

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_title'] = 'CertiPro | Temario'
        context['page_title'] = 'Temario'
        context['content_title'] = 'Temas registrados'
        context['url_reporte'] = 'tablero:index'
        context['url_admin'] = 'admin:temario_tema_changelist'
        return context


class VistaTemarioEnDetalle(LoginRequiredMixin, DetailView):
    """Renderiza los detalles de un tema (ediciones, horas académicas y
    contenidos programáticos).

    Args:
        LoginRequiredMixin (class): Verifica que el usuario esté autentificado.
        DetailView (class): Vista genérica detallada de Django.
    """
    model = Tema
    template_name = 'temario/detalle-temario.html'

temario/templates/temario/botones_acciones.html
<a href="#" class="btn btn-primary btn-circle btn-sm btn_info" title="Ver más" data-url-detalle="{% url 'temario:detalle' record.id %}">
  <i class="fas fa-eye"></i>
</a>
<a href="{% url 'admin:temario_tema_change' record.id %}" target="_blank" class="btn btn-success btn-circle btn-sm" title="Editar en el Administrador">
  <i class="fas fa-edit"></i>
</a>

temario/templates/temario/detalle-temario.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="moreInfoModalLabel"><em>{{ object.titulo }}</em></h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <nav>
          {% with cantidad_ediciones=object.detalletema_set.count  %}
          {% if cantidad_ediciones == 1 %}
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            {% for tema in object.detalletema_set.all %}
            <a class="nav-item nav-link active" id="nav-{{ tema.id }}-tab" data-toggle="tab" href="#nav-{{ tema.id }}" role="tab" aria-controls="nav-{{ tema.id }}" aria-selected="false">{{ tema.edicion }}</a>
            {% endfor %}
          </div>
          <div class="tab-content" id="nav-tabContent">
            {% for tema in object.detalletema_set.all %}
            <div class="tab-pane fade show active mt-1" id="nav-{{ tema.id }}" role="tabpanel" aria-labelledby="nav-{{ tema.id }}-tab">{{ tema.contenido|safe }}</div>
            {% endfor %}
          </div>
          {% else %}
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            {% for tema in object.detalletema_set.all %}
            <a class="nav-item nav-link" id="nav-{{ tema.id }}-tab" data-toggle="tab" href="#nav-{{ tema.id }}" role="tab" aria-controls="nav-{{ tema.id }}" aria-selected="false">{{ tema.edicion }}</a>
            {% endfor %}
          </div>
          <div class="tab-content" id="nav-tabContent">
            {% for tema in object.detalletema_set.all %}
            <div class="tab-pane fade  mt-1" id="nav-{{ tema.id }}" role="tabpanel" aria-labelledby="nav-{{ tema.id }}-tab">{{ tema.contenido|safe }}</div>
            {% endfor %}
          </div>
          {% endif %}
          {% endwith %}
        </nav>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cerrar</button>
        <a class="btn btn-success" href="{% url 'admin:temario_tema_change' object.id %}" target="_blank">Editar</a>
      </div>
    </div>
  </div>

temario/templates/temario/lista-temario.html
{% extends "tablero/base.html" %}

{% block nav-item-temario %}<li class="nav-item active">{% endblock nav-item-temario %}